## FOS
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

application_api_user:
    resource: "@ApplicationApiUserBundle/Controller/"
    type:     annotation
    prefix:   /

application_api_default:
    resource: "@ApplicationApiDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

## Security
#login:
#    pattern:   /login
#    defaults:  { _controller: ApplicationApiUserBundle:Security:login }
#
#login_check:
#    pattern:   /login_check
#
#logout:
#    pattern:   /logout


## Avalanche image
_imagine:
    resource: .
    type:     imagine



