application_api_user:
    resource: "@ApplicationApiUserBundle/Controller/"
    type:     annotation
    prefix:   /

application_api_default:
    resource: "@ApplicationApiDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

## Security
login:
    pattern:   /login
    defaults:  { _controller: ApplicationApiUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

